apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      imagePullSecrets:
        - name: my-registry-key
      containers:
      - name: student-app
        image: vasanth4747/login-animation:latest  # Updated image name
        ports:
        - containerPort: 80
